[changes]
modules = [
    "src/utilities/ai_calls",
    "src/utilities/ai_message_generator.rs",
    "src/utilities/version_operations.rs",
]
description = """
Add AI-powered changeset message generation with support for OpenAI and Gemini providers. \
Implement environment-based configuration through single API_KEY and MODEL variables. \
Include automatic version calculation based on semantic versioning rules."""

[changeset]
change_type = "MINOR"
tag = "Feature"
version = "0.1.0"
