[changeset]
change_type = "MINOR"
tag = "Add"
version = "0.1.0"

[changes]
modules = ["GitHub Workflows"]
description = "Add a GitHub workflow for automatic Pull Requests opening and automatic updates"
